import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        // Custom nature palette
        "sky-mist": "hsl(var(--sky-mist))",
        "sky-mid": "hsl(var(--sky-mid))",
        "sky-sunset": "hsl(var(--sky-sunset))",
        "mountain-ink": "hsl(var(--mountain-ink))",
        "mountain-mid": "hsl(var(--mountain-mid))",
        "mountain-light": "hsl(var(--mountain-light))",
        "river-teal": "hsl(var(--river-teal))",
        "river-light": "hsl(var(--river-light))",
        "sunset-gold": "hsl(var(--sunset-gold))",
        "paper-base": "hsl(var(--paper-base))",
        "paper-warm": "hsl(var(--paper-warm))",
        "terracotta": "hsl(var(--terracotta))",
        "forest-green": "hsl(var(--forest-green))",
        "forest-light": "hsl(var(--forest-light))",
        "ocean-deep": "hsl(var(--ocean-deep))",
        "ocean-mid": "hsl(var(--ocean-mid))",
        "ocean-light": "hsl(var(--ocean-light))",
        "sand": "hsl(var(--sand))",
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
      },
      fontFamily: {
        display: ['"Cormorant Garamond"', 'serif'],
        body: ['"Instrument Sans"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "float": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-12px)" },
        },
        "drift": {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(calc(100vw + 100%))" },
        },
        "wave": {
          "0%, 100%": { transform: "translateX(0) scaleY(1)" },
          "50%": { transform: "translateX(-25px) scaleY(1.05)" },
        },
        "bird-fly": {
          "0%": { transform: "translateX(-50px) translateY(0)" },
          "25%": { transform: "translateX(25vw) translateY(-15px)" },
          "50%": { transform: "translateX(50vw) translateY(5px)" },
          "75%": { transform: "translateX(75vw) translateY(-10px)" },
          "100%": { transform: "translateX(105vw) translateY(0)" },
        },
        "flutter": {
          "0%, 100%": { transform: "translateY(0) rotate(0deg) scale(1)" },
          "25%": { transform: "translateY(-8px) rotate(5deg) scale(1.05)" },
          "75%": { transform: "translateY(4px) rotate(-3deg) scale(0.98)" },
        },
        "ripple": {
          "0%": { transform: "scale(0)", opacity: "0.6" },
          "100%": { transform: "scale(4)", opacity: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "float": "float 4s ease-in-out infinite",
        "float-slow": "float 6s ease-in-out infinite",
        "float-slower": "float 8s ease-in-out infinite",
        "drift": "drift 30s linear infinite",
        "drift-slow": "drift 45s linear infinite",
        "wave": "wave 3s ease-in-out infinite",
        "bird-fly": "bird-fly 12s linear infinite",
        "flutter": "flutter 3s ease-in-out infinite",
        "ripple": "ripple 2s ease-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
